let sb, companies=[];const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
async function boot(){if(!window.APP_CONFIG?.supabaseUrl||!window.APP_CONFIG?.supabasePublishableKey){$('#loginMsg').textContent='Site configuration is not available yet.';return}sb=supabase.createClient(APP_CONFIG.supabaseUrl,APP_CONFIG.supabasePublishableKey);const {data:{session}}=await sb.auth.getSession();if(session)showApp(session);sb.auth.onAuthStateChange((_e,s)=>s?showApp(s):showLogin())}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMsg').textContent='Signing in…';const {data,error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#loginMsg').textContent=error?error.message:'';if(data?.session)showApp(data.session)});
$('#signOut').addEventListener('click',()=>sb.auth.signOut());function showLogin(){$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
async function showApp(session){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#userEmail').textContent=session.user.email;await loadData()}
async function loadData(){const [c,j,a,act]=await Promise.all([sb.from('companies').select('*').eq('active',true).order('company_name'),sb.from('jobs').select('id,decision,job_status,job_title'),sb.from('applications').select('id,status'),sb.from('activities').select('id,follow_up_required,follow_up_date,completed')]);if(c.error){$('#status').textContent='Database connection error: '+c.error.message;return}companies=c.data||[];$('#companyCount').textContent=companies.length;$('#newJobs').textContent=(j.data||[]).filter(x=>x.decision==='New'&&x.job_status==='Open').length;$('#activeApps').textContent=(a.data||[]).filter(x=>!['Rejected','Withdrawn','Offer Accepted','Closed'].includes(x.status)).length;const today=new Date().toISOString().slice(0,10);$('#followups').textContent=(act.data||[]).filter(x=>x.follow_up_required&&!x.completed&&x.follow_up_date&&x.follow_up_date<=today).length;$('#status').textContent='Connected. Company research is loading from Supabase, not from the old data.js file.';renderCompanies(companies);renderJobs(j.data||[])}
function renderCompanies(rows){$('#companiesList').innerHTML=rows.map(c=>'<article class="company-card"><b>'+esc(c.company_name)+'</b><span>'+esc(c.priority||'Uncategorized')+(c.industry?' · '+esc(c.industry):'')+'</span></article>').join('')}
function renderJobs(rows){$('#jobsList').innerHTML=rows.length?rows.map(j=>'<div class="company-card"><b>'+esc(j.job_title)+'</b><span>'+esc(j.decision||'New')+' · '+esc(j.job_status||'Open')+'</span></div>').join(''):'<p>No jobs in the database yet.</p>'}
$('#companySearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderCompanies(companies.filter(c=>(c.company_name+' '+(c.industry||'')+' '+(c.priority||'')).toLowerCase().includes(q)))});
$$('.nav').forEach(b=>b.addEventListener('click',()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden');$('#viewTitle').textContent=b.textContent}));function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}boot();